"""
Named presets for Martingale.
Each preset is a dict of hyperparameter overrides applied on top of defaults.
"""

PRESETS = {
    'original': {
        'base_size_value':1.0,
        'signal_mode': 'none',
        'direction_bias': 'long_only',
        'sizing_curve': 'geometric',
        'sizing_factor': 2.0,
        'max_levels': 6,
        'hedge_mode': 'fixed_pips',
        'hedge_value': 10.0,
        'tp_mode': 'fixed_pips',
        'tp_value': 20.0,
    },

    'v2': {
        'signal_mode': 'ema_cross',
        'ema_fast': 8,
        'ema_slow': 21,
        'sizing_curve': 'sqrt',
        'sizing_factor': 2.0,
        'max_levels': 6,
        'hedge_mode': 'atr_based',
        'hedge_value': 1.5,
        'hedge_atr_period': 14,
        'tp_mode': 'bucket_pct',
        'tp_value': 0.1,
        'session_filter': 'london_ny',
        'cooldown_mode': 'bars',
        'cooldown_value': 10,
        'max_daily_loss_pct': 2.0,
        'max_consec_busts': 3,
    },

    'momentum': {
        'signal_mode': 'indicator',
        'ind_name': 'mom',
        'ind_period': 14,
        'ind_rule': 'cross_zero',
        'sizing_curve': 'sqrt',
        'sizing_factor': 2.0,
        'max_levels': 8,
        'hedge_mode': 'atr_based',
        'hedge_value': 1.5,
        'hedge_atr_period': 14,
        'tp_mode': 'bucket_pct',
        'tp_value': 0.1,
        'session_filter': 'london_ny',
        'trend_filter': 'adx_gate',
        'trend_filter_threshold': 20,
    },

    'mean_reversion': {
        'signal_mode': 'dual_indicator',
        'ind_name': 'rsi',
        'ind_period': 14,
        'ind_rule': 'ob_os',
        'ind_long_threshold': 25,
        'ind_short_threshold': 75,
        'ind2_name': 'bollinger',
        'ind2_period': 20,
        'ind2_rule': 'agree',
        'sizing_curve': 'sqrt',
        'sizing_factor': 1.5,
        'max_levels': 6,
        'hedge_mode': 'atr_based',
        'hedge_value': 1.0,
        'hedge_atr_period': 14,
        'tp_mode': 'fixed_pips',
        'tp_value': 15.0,
        'vol_filter': 'atr_range',
        'vol_filter_min': 3.0,
        'vol_filter_max': 30.0,
        'cooldown_mode': 'bars',
        'cooldown_value': 10,
        'max_daily_loss_pct': 2.0,
    },

    # P4: d'Alembert null-hypothesis baseline (Dimitrov & Shafer 2025)
    # Random entry with identical sizing/TP to v2.
    # If SurefireHedge doesn't meaningfully beat this, the EMA crossover adds no value.
    'dalembert_baseline': {
        'signal_mode': 'random',
        'direction_bias': 'both',
        'sizing_curve': 'sqrt',
        'sizing_factor': 2.0,
        'max_levels': 6,
        'hedge_mode': 'atr_based',
        'hedge_value': 1.5,
        'hedge_atr_period': 14,
        'tp_mode': 'bucket_pct',
        'tp_value': 0.1,
        'session_filter': 'london_ny',
        'cooldown_mode': 'bars',
        'cooldown_value': 10,
        'max_daily_loss_pct': 2.0,
        'max_consec_busts': 3,
    },
}
