"""
Named presets for UniversalMartingale.
Each preset is a dict of hyperparameter overrides applied on top of defaults.
"""

PRESETS = {
    'raw': {
        'signal_mode': 'random',
        'direction_bias': 'both',
        'sizing_curve': 'geometric',
        'sizing_factor': 2.0,
        'base_size_mode': 'fixed',
        'base_size_value': 1.0,
        'max_levels': 6,
        'hedge_mode': 'fixed_pips',
        'hedge_value': 10.0,
        'tp_mode': 'fixed_pips',
        'tp_value': 20.0,
        'session_filter': 'any',
        'vol_filter': 'none',
        'trend_filter': 'none',
        'spread_filter': 'none',
        'cooldown_mode': 'none',
        'abort_mode': 'none',
        'max_daily_loss_pct': 0.0,
        'max_consec_busts': 0,
        'partial_close': 'none',
        'breakeven_mode': 'none',
    },

    'surefire_v1': {
        'signal_mode': 'random',
        'sizing_curve': 'sqrt',
        'sizing_factor': 2.0,
        'max_levels': 12,
        'hedge_mode': 'fixed_pips',
        'hedge_value': 10.0,
        'tp_mode': 'fixed_pips',
        'tp_value': 20.0,
        'session_filter': 'any',
    },

    'surefire_v2': {
        'signal_mode': 'ema_cross',
        'ema_fast': 8,
        'ema_slow': 21,
        'sizing_curve': 'sqrt',
        'sizing_factor': 2.0,
        'max_levels': 6,
        'hedge_mode': 'atr_based',
        'hedge_value': 1.5,
        'hedge_atr_period': 14,
        'tp_mode': 'bucket_pct',
        'tp_value': 0.1,
        'session_filter': 'london_ny',
        'cooldown_mode': 'bars',
        'cooldown_value': 10,
        'max_daily_loss_pct': 2.0,
        'max_consec_busts': 3,
    },

    'conservative': {
        'signal_mode': 'ema_rsi',
        'ema_fast': 8,
        'ema_slow': 21,
        'rsi_period': 14,
        'rsi_ob': 70,
        'rsi_os': 30,
        'sizing_curve': 'sqrt',
        'sizing_factor': 1.5,
        'max_levels': 8,
        'hedge_mode': 'atr_based',
        'hedge_value': 2.0,
        'hedge_atr_period': 14,
        'tp_mode': 'bucket_pct',
        'tp_value': 0.05,
        'session_filter': 'overlap',
        'vol_filter': 'atr_range',
        'trend_filter': 'adx_gate',
        'trend_filter_threshold': 25.0,
        'cooldown_mode': 'bars',
        'cooldown_value': 20,
        'max_daily_loss_pct': 1.5,
        'max_consec_busts': 2,
        'abort_mode': 'level_threshold',
        'abort_level': 6,
    },

    'aggressive': {
        'signal_mode': 'random',
        'sizing_curve': 'geometric',
        'sizing_factor': 2.5,
        'max_levels': 4,
        'hedge_mode': 'fixed_pips',
        'hedge_value': 15.0,
        'tp_mode': 'fixed_pips',
        'tp_value': 30.0,
        'session_filter': 'any',
        'max_daily_loss_pct': 5.0,
    },

    'fibonacci': {
        'signal_mode': 'ema_cross',
        'ema_fast': 8,
        'ema_slow': 21,
        'sizing_curve': 'fibonacci',
        'max_levels': 10,
        'hedge_mode': 'fibonacci_levels',
        'tp_mode': 'atr_based',
        'tp_value': 2.0,
        'tp_atr_period': 14,
        'session_filter': 'london_ny',
    },

    'scalper': {
        'signal_mode': 'bollinger',
        'bb_period': 20,
        'bb_std': 2.0,
        'sizing_curve': 'linear',
        'sizing_factor': 1.0,
        'max_levels': 5,
        'hedge_mode': 'atr_based',
        'hedge_value': 0.5,
        'hedge_atr_period': 10,
        'tp_mode': 'fixed_pips',
        'tp_value': 5.0,
        'session_filter': 'overlap',
        'spread_filter': 'max_spread',
        'spread_filter_max': 2.0,
        'cooldown_mode': 'bars',
        'cooldown_value': 5,
    },

    'momentum': {
        'signal_mode': 'indicator',
        'ind_name': 'mom',
        'ind_period': 14,
        'ind_rule': 'cross_zero',
        'sizing_curve': 'sqrt',
        'sizing_factor': 2.0,
        'max_levels': 8,
        'hedge_mode': 'atr_based',
        'hedge_value': 1.5,
        'hedge_atr_period': 14,
        'tp_mode': 'bucket_pct',
        'tp_value': 0.1,
        'session_filter': 'london_ny',
        'trend_filter': 'adx_gate',
        'trend_filter_threshold': 20,
    },

    'mean_reversion': {
        'signal_mode': 'dual_indicator',
        'ind_name': 'rsi',
        'ind_period': 14,
        'ind_rule': 'ob_os',
        'ind_long_threshold': 25,
        'ind_short_threshold': 75,
        'ind2_name': 'bollinger',
        'ind2_period': 20,
        'ind2_rule': 'agree',
        'sizing_curve': 'sqrt',
        'sizing_factor': 1.5,
        'max_levels': 6,
        'hedge_mode': 'atr_based',
        'hedge_value': 1.0,
        'hedge_atr_period': 14,
        'tp_mode': 'fixed_pips',
        'tp_value': 15.0,
        'vol_filter': 'atr_range',
        'vol_filter_min': 3.0,
        'vol_filter_max': 30.0,
        'cooldown_mode': 'bars',
        'cooldown_value': 10,
        'max_daily_loss_pct': 2.0,
    },

    'trend_rider': {
        'signal_mode': 'indicator',
        'ind_name': 'trendflex',
        'ind_period': 20,
        'ind_rule': 'cross_zero',
        'sizing_curve': 'geometric',
        'sizing_factor': 2.0,
        'max_levels': 10,
        'hedge_mode': 'percentage',
        'hedge_value': 0.3,
        'tp_mode': 'trailing',
        'tp_value': 15.0,
        'session_filter': 'london_ny',
        'trend_filter': 'ema_slope',
        'trend_filter_period': 50,
        'equity_curve_filter': 'above_ema',
        'equity_ema_period': 30,
        'max_weekly_loss_pct': 5.0,
    },

    'phase3_optimized': {
        # Phase 3 research-validated config (walk-forward tested on 2024-2025)
        # Entry: EMA crossover + DM directional gate + confidence filter
        'signal_mode': 'ema_cross',
        'ema_fast': 8,
        'ema_slow': 21,
        'entry_on_crossover': 'yes',
        'direction_bias': 'both',
        # Sizing: fibonacci at 10 levels, capital-aware base
        'sizing_curve': 'fibonacci',
        'sizing_factor': 2.0,
        'base_size_mode': 'capital_aware',
        'max_bust_dd_pct': 20,
        'max_levels': 10,
        # Grid: 15 pip hedge (proven optimal in script 29)
        'hedge_mode': 'fixed_pips',
        'hedge_value': 15.0,
        # TP: 15 pips (matched to hedge for ~1:1 risk-reward per level)
        'tp_mode': 'fixed_pips',
        'tp_value': 15.0,
        # Filters: DM gate + NATR vol filter + confidence gate
        'trend_filter': 'dm_gate',
        'trend_filter_period': 14,
        'trend_filter_threshold': 0,  # Any directional movement
        'vol_filter': 'natr_min',
        'vol_filter_period': 14,
        'vol_filter_min': 0.02,  # Skip very low vol (bottom 20%)
        'confidence_gate': 'enabled',
        'confidence_threshold': 0.4,  # Conservative; 0.5 for aggressive
        # Session: London + NY (most liquid)
        'session_filter': 'london_ny',
        'spread_filter': 'max_spread',
        'spread_filter_max': 3.0,
        # Risk: weekly loss cap, no abort (proven destructive)
        'max_weekly_loss_pct': 10.0,
        'abort_mode': 'none',
        'cooldown_mode': 'bars',
        'cooldown_value': 5,
    },
}
